# Local dev only. Wiki at http://localhost:8080

services:
  mariadb:
    image: mariadb:12
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  install:
    build: .
    command: maintenance/run install --dbserver=${DB_SERVER} --dbname=${DB_NAME} --dbuser=${DB_USER} --dbpass=${DB_PASSWORD} --server=http://${DOMAIN_NAME} --scriptpath= --pass=adminadmin Admin Admin
    restart: no
    env_file: .env
    volumes:
      - ./extensions/AEPedia:/var/www/html/extensions/AEPedia
    profiles:
      - install
    depends_on:
      - mariadb

  update:
    build: .
    command: maintenance/run update --quick
    restart: no
    env_file: .env
    volumes:
      - ./extensions/AEPedia:/var/www/html/extensions/AEPedia
      - ./config/LocalSettings.prod.php:/var/www/html/LocalSettings.php
    profiles:
      - update
    depends_on:
      - mariadb

  mediawiki:
    build: .
    ports:
      - "8080:80"
    env_file: .env
    volumes:
      - ./extensions/AEPedia:/var/www/html/extensions/AEPedia
      - ./config/LocalSettings.prod.php:/var/www/html/LocalSettings.php
    depends_on:
      - mariadb
